name: AliExpress Auto Collect Coins

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install selenium

    - name: Run Collector
      env:
        ALIE_COOKIE: ${{ secrets.ALIE_COOKIE }}
      run: python collect_coins.py

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-images
        path: "*.png"
